name: 'Act1'
inputs:
  username:
    description: "is false"
    required: true
runs:
  using: "composite"
  steps:
    # Test to print Act 1
      
    - name:  Test if true
      if: always() && inputs.username
      run: echo "It is True"
      shell: bash
