name: 'Act 2'

runs:
  using: "composite"
  steps:
    - name: Tesit
      run: echo "Hi from Act 2"
      shell: bash
      
    - name: Act1 test
      id: test-ot
      uses: ./.github/composite-actions/act1
  
    - name: check
      if: always() && steps.test-ot.outcome == 'success'
      run: echo "Checked"
