name: test
on: [push, pull_request]

jobs:
  generate-version-upgrade-tests:
    name: Generate Version Upgrade Tests
    runs-on: ubuntu-latest
    outputs:
      upgrade-path-list: ${{ steps.generate-upgrade-path.outputs.upgrade-path-list }}
    steps:
      - uses: actions/checkout@v2
      
      - name: "Read and setup upgrade path list from configuration"
        id: generate-upgrade-path
        run: |
          config="'$(yq -o=json ${{ github.workspace }}/.github/upgrade-test-configuration.yml)'"
          config=$(echo $config | sed "s/\"/\\\\\"/g")
          UPGRADE_PATH_LIST=$(node -e "let k = JSON.parse($config); let p = k['upgrade-version'].map((itm, index) => ({ id: index, path: itm.map(i => i.version.toString().replace(/[.]/g, \"_\")), title: itm.map(i => i.version.toString().replace(/[.]/g, \"_\")).join(\"-\") })); console.log(JSON.stringify(p));")
          echo "::set-output name=upgrade-path-list::$UPGRADE_PATH_LIST"
  tests:
    name: test
    strategy:
      matrix:
        version: ${{ fromJson(needs.generate-version-upgrade-tests.outputs.upgrade-path-list) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install yq - yaml parser
        run: sudo snap install yq
      
      - name: read temp length
        id: read-temp-len
        run: yq '."upgrade-version"' .github/upgrade-test-configuration.yml
      
      - name: read length
        id: read-len
        run: >
            echo "::set-output name=items::$(
              yq '."upgrade-version"' .github/upgrade-test-configuration.yml
            )"
            
      - name: sineina
        run: | 
            echo "check this : ${{ matrix.version.path[0] }}"
          
      - name: do changes
        id: do-changes
        run: |
          echo "    # Test to print Act 1\n    - name:  Test if true\n      if: always() && inputs.username\n      run: echo 'It is True'\n      shell: bash"  >> ./.github/composite-actions/act1/action.yml
        shell: bash
        
      - name: print changes
        run: | 
          cat .github/composite-actions/act1/action.yml
          echo ${{ matrix.version }}
          
      - name: read
        id: read
        run: yq '."13.4".engine_branch' .github/version-branch-template.yml
        
      - name: act test
        id: act-test
        uses: ./.github/composite-actions/act2
        
      - name: final
        id: final 
        run: echo "done"
