name: test
on: [push, pull_request]

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install yq - yaml parser
        run: pip3 install yq
      
      - name: read temp length
        id: read-temp-len
        run: yq -r '."upgrade-version"' .github/upgrade-test-configuration.yml
      
      - name: read length
        id: read-len
        run: >
            echo "::set-output name=items::$(
              yq -r '."upgrade-version"' .github/upgrade-test-configuration.yml
            )"

      - name: add hellos
        run: |
          for n in ${{ steps.read-len.outputs.items }}; 
          do
            sudo sed -i "s/# Test to print Act 1/# Test to print Act 1 \n\t- name: Test $n \n\t  id: test-$n \n\t  run: echo 'Hello there act 1' \n\t  shell: bash \n /g" .github/composite-actions/act1/action.yml
          done
          
      - name: print changes
        run: | 
          cat .github/composite-actions/act1/action.yml
        
      - name: read
        id: read
        run: yq -r '."13.4".engine_branch' .github/version-branch-template.yml
        
      - name: act test
        id: act-test
        uses: ./.github/composite-actions/act2
        
      - name: final
        id: final 
        run: echo "done"
