name: test-job
on: [push, pull_request]

jobs:
  job-name:
    name: Print the GitHub context
    runs-on: ubuntu-latest
    steps:
      - name: someh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
