name: test
on: [push, pull_request]

jobs:
  tests:
    name: test
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install yq - yaml parser
        run: sudo snap install yq
      
      - name: read temp length
        id: read-temp-len
        run: yq '."upgrade-version"' .github/upgrade-test-configuration.yml
      
      - name: read length
        id: read-len
        run: >
            echo "::set-output name=items::$(
              yq '."upgrade-version"' .github/upgrade-test-configuration.yml
            )"
          
      - name: print changes
        run: | 
          cat .github/composite-actions/act1/action.yml
          echo ${{ matrix.version }}
          
      - name: read
        id: read
        run: yq '."13.4".engine_branch' .github/version-branch-template.yml
        
      - name: act test
        id: act-test
        uses: ./.github/composite-actions/act2
        
      - name: final
        id: final 
        run: echo "done"
