name: test
on: [push, pull_request]

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install yq - yaml parser
        run: pip3 install yq
      
      - name: read length
        id: read-len
        run: >
          echo "::set-output name=lenth::$(
            yq -r '."upgrade-version" | length' .github/upgrade-test-configuration.yml
          )"
        
      - name: add hellos
        run: |
          for n in {1..${{ steps.read-len.outputs.lenth }}}; 
          do
            sudo sed -i 's/# Test to print Act 1/# Test to print Act 1
                                                  - name: Test${{ steps.read-len.outputs.lenth }}
                                                    id: test${{ steps.read-len.outputs.lenth }}
                                                    run: echo "Hello there act 1"
                                                    shell: bash/g' .github/composite-actions/act1/action.yml
          done
          
      - name: print changes
        run: | 
          cat .github/composite-actions/act1/action.yml
        
      - name: read
        id: read
        run: yq -r '."13.4".engine_branch' .github/version-branch-template.yml
        
      - name: act test
        id: act-test
        uses: ./.github/composite-actions/act2
        
      - name: final
        id: final 
        run: echo "done"
