name: Version Upgrade Test Framework
on: [push, pull_request]

jobs:
  job-name:
    name: Print the GitHub context
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    run: echo "$GITHUB_CONTEXT"
